version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - forex-platform-network

networks:
  forex-platform-network:
    driver: bridge
