version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./:/app
    networks:
      - forex-platform-network

networks:
  forex-platform-network:
    driver: bridge