repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-import-order',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-return',
            'flake8-simplify',
        ]
        args: ["--max-line-length=88", "--extend-ignore=E203"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-requests',
            'types-PyYAML',
            'types-python-dateutil',
        ]
        args: ["--ignore-missing-imports"]
        exclude: "^tests/"

-   repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
    -   id: pylint
        args: ["--rcfile=tools/linting/pylintrc"]
        exclude: "^tests/"

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
        args: ["--config", "tools/linting/.prettierrc.json"]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.42.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        args: ["--config", "tools/linting/.eslintrc.js", "--fix"]