# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from trading_gateway_service import trading_gateway_pb2 as trading__gateway__service_dot_trading__gateway__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trading_gateway_service/trading_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingGatewayServiceStub(object):
    """Service for managing trading orders.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteOrder = channel.unary_unary(
                '/trading_gateway_service.TradingGatewayService/ExecuteOrder',
                request_serializer=trading__gateway__service_dot_trading__gateway__pb2.OrderRequest.SerializeToString,
                response_deserializer=trading__gateway__service_dot_trading__gateway__pb2.ExecutionReport.FromString,
                _registered_method=True)


class TradingGatewayServiceServicer(object):
    """Service for managing trading orders.
    """

    def ExecuteOrder(self, request, context):
        """Executes a trading order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteOrder,
                    request_deserializer=trading__gateway__service_dot_trading__gateway__pb2.OrderRequest.FromString,
                    response_serializer=trading__gateway__service_dot_trading__gateway__pb2.ExecutionReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading_gateway_service.TradingGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading_gateway_service.TradingGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingGatewayService(object):
    """Service for managing trading orders.
    """

    @staticmethod
    def ExecuteOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_gateway_service.TradingGatewayService/ExecuteOrder',
            trading__gateway__service_dot_trading__gateway__pb2.OrderRequest.SerializeToString,
            trading__gateway__service_dot_trading__gateway__pb2.ExecutionReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
