# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trading_gateway_service/trading_gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'trading_gateway_service/trading_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-trading_gateway_service/trading_gateway.proto\x12\x17trading_gateway_service\x1a\x0c\x63ommon.proto\"\xc8\x01\n\x0cOrderRequest\x12\x1e\n\x08order_id\x18\x01 \x01(\x0b\x32\x0c.common.UUID\x12\x19\n\x11instrument_symbol\x18\x02 \x01(\t\x12\x36\n\norder_type\x18\x03 \x01(\x0e\x32\".trading_gateway_service.OrderType\x12\x10\n\x08quantity\x18\x04 \x01(\x01\x12\r\n\x05price\x18\x05 \x01(\x01\x12$\n\ttimestamp\x18\x06 \x01(\x0b\x32\x11.common.Timestamp\"\x83\x02\n\x0f\x45xecutionReport\x12\x1e\n\x08order_id\x18\x01 \x01(\x0b\x32\x0c.common.UUID\x12\"\n\x0c\x65xecution_id\x18\x02 \x01(\x0b\x32\x0c.common.UUID\x12\x34\n\x06status\x18\x03 \x01(\x0e\x32$.trading_gateway_service.OrderStatus\x12\x17\n\x0f\x66illed_quantity\x18\x04 \x01(\x01\x12\x15\n\raverage_price\x18\x05 \x01(\x01\x12$\n\ttimestamp\x18\x06 \x01(\x0b\x32\x11.common.Timestamp\x12\x14\n\x07message\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message*>\n\tOrderType\x12\x1a\n\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06MARKET\x10\x01\x12\t\n\x05LIMIT\x10\x02*w\n\x0bOrderStatus\x12\x1c\n\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\n\n\x06\x46ILLED\x10\x02\x12\x14\n\x10PARTIALLY_FILLED\x10\x03\x12\r\n\tCANCELLED\x10\x04\x12\x0c\n\x08REJECTED\x10\x05\x32x\n\x15TradingGatewayService\x12_\n\x0c\x45xecuteOrder\x12%.trading_gateway_service.OrderRequest\x1a(.trading_gateway_service.ExecutionReportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trading_gateway_service.trading_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERTYPE']._serialized_start=553
  _globals['_ORDERTYPE']._serialized_end=615
  _globals['_ORDERSTATUS']._serialized_start=617
  _globals['_ORDERSTATUS']._serialized_end=736
  _globals['_ORDERREQUEST']._serialized_start=89
  _globals['_ORDERREQUEST']._serialized_end=289
  _globals['_EXECUTIONREPORT']._serialized_start=292
  _globals['_EXECUTIONREPORT']._serialized_end=551
  _globals['_TRADINGGATEWAYSERVICE']._serialized_start=738
  _globals['_TRADINGGATEWAYSERVICE']._serialized_end=858
# @@protoc_insertion_point(module_scope)
