# API Gateway Configuration

# Service information
service:
  name: api-gateway
  version: 1.0.0
  description: API Gateway for the Forex Trading Platform

# Server configuration
server:
  host: 0.0.0.0
  port: 8000
  debug: false

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/api-gateway.log
  rotation: 10MB
  retention: 30 days

# Authentication configuration
auth:
  secret_key: ${JWT_SECRET_KEY}
  algorithm: HS256
  public_paths:
    - /health
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/refresh
    - /docs*
    - /redoc*
    - /openapi.json

# Rate limiting configuration
rate_limit:
  enabled: true
  limit: 100
  window: 60
  exempt_paths:
    - /health
    - /docs*
    - /redoc*
    - /openapi.json

# CORS configuration
cors:
  allow_origins:
    - http://localhost:3000
    - https://app.forexplatform.com
  allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow_headers:
    - Content-Type
    - Authorization
    - X-Correlation-ID
    - X-Request-ID
  allow_credentials: true
  max_age: 600

# XSS protection configuration
xss_protection:
  enabled: true
  exempt_paths:
    - /health
    - /docs*
    - /redoc*
    - /openapi.json

# CSRF protection configuration
csrf_protection:
  enabled: true
  cookie_name: csrf_token
  header_name: X-CSRF-Token
  cookie_max_age: 86400  # 24 hours
  secure: true
  same_site: lax
  exempt_paths:
    - /health
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/refresh
    - /docs*
    - /redoc*
    - /openapi.json

# Security headers configuration
security_headers:
  enabled: true
  exempt_paths:
    - /health
  csp_directives:
    default-src:
      - "'self'"
    script-src:
      - "'self'"
    style-src:
      - "'self'"
    img-src:
      - "'self'"
      - "data:"
    font-src:
      - "'self'"
    connect-src:
      - "'self'"
    frame-src:
      - "'none'"
    object-src:
      - "'none'"
    base-uri:
      - "'self'"
    form-action:
      - "'self'"
    frame-ancestors:
      - "'none'"
    upgrade-insecure-requests: []
  x_content_type_options: nosniff
  x_frame_options: DENY
  x_xss_protection: "1; mode=block"
  referrer_policy: strict-origin-when-cross-origin
  hsts_max_age: 31536000  # 1 year
  hsts_include_subdomains: true
  hsts_preload: true
  permissions_policy:
    accelerometer:
      - "()"
    camera:
      - "()"
    geolocation:
      - "()"
    microphone:
      - "()"
    payment:
      - "()"

# Service clients configuration
service_clients:
  market_data_service:
    base_url: http://market-data-service:8001
    timeout: 30.0
    retry:
      max_retries: 3
      initial_delay: 1.0
      backoff_factor: 2.0
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 60.0

  analysis_engine_service:
    base_url: http://analysis-engine-service:8002
    timeout: 30.0
    retry:
      max_retries: 3
      initial_delay: 1.0
      backoff_factor: 2.0
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 60.0

  trading_gateway_service:
    base_url: http://trading-gateway-service:8003
    timeout: 30.0
    retry:
      max_retries: 3
      initial_delay: 1.0
      backoff_factor: 2.0
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 60.0

  feature_store_service:
    base_url: http://feature-store-service:8004
    timeout: 30.0
    retry:
      max_retries: 3
      initial_delay: 1.0
      backoff_factor: 2.0
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 60.0