apiVersion: v1
kind: Service
metadata:
  labels:
    app: risk-management-service
  name: risk-management-service
spec:
  ports:
  - name: http
    port: 8003
    targetPort: 8003
  selector:
    app: risk-management-service
