# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/error_types.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common/error_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ommon/error_types.proto\x12\x0c\x66orex.common\"T\n\x0b\x45rrorDetail\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x04\x63ode\x18\x03 \x01(\x0e\x32\x17.forex.common.ErrorCode\"\xf2\x01\n\rErrorResponse\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x17.forex.common.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12*\n\x07\x64\x65tails\x18\x04 \x03(\x0b\x32\x19.forex.common.ErrorDetail\x12\x39\n\x07\x63ontext\x18\x05 \x03(\x0b\x32(.forex.common.ErrorResponse.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xc1\x02\n\tErrorCode\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x11\n\rINVALID_INPUT\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\x12\x19\n\x15\x41UTHENTICATION_FAILED\x10\x03\x12\x18\n\x14\x41UTHORIZATION_FAILED\x10\x04\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x05\x12\x0c\n\x08\x43ONFLICT\x10\x06\x12\x12\n\x0eINTERNAL_ERROR\x10\x07\x12\x17\n\x13SERVICE_UNAVAILABLE\x10\x08\x12\x0b\n\x07TIMEOUT\x10\t\x12\x17\n\x13RATE_LIMIT_EXCEEDED\x10\n\x12\x0f\n\x0b\x42\x41\x44_GATEWAY\x10\x0b\x12\x14\n\x10VALIDATION_ERROR\x10\x0c\x12\x12\n\x0e\x44\x41TABASE_ERROR\x10\r\x12\x1a\n\x16\x45XTERNAL_SERVICE_ERROR\x10\x0e\x42K\n\x18\x63om.olevar2.forex.commonP\x01Z-github.com/olevar2/MD/common-lib/proto/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.error_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.olevar2.forex.commonP\001Z-github.com/olevar2/MD/common-lib/proto/common'
  _globals['_ERRORRESPONSE_CONTEXTENTRY']._loaded_options = None
  _globals['_ERRORRESPONSE_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ERRORCODE']._serialized_start=374
  _globals['_ERRORCODE']._serialized_end=695
  _globals['_ERRORDETAIL']._serialized_start=42
  _globals['_ERRORDETAIL']._serialized_end=126
  _globals['_ERRORRESPONSE']._serialized_start=129
  _globals['_ERRORRESPONSE']._serialized_end=371
  _globals['_ERRORRESPONSE_CONTEXTENTRY']._serialized_start=325
  _globals['_ERRORRESPONSE_CONTEXTENTRY']._serialized_end=371
# @@protoc_insertion_point(module_scope)
