apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        username: elastic
        password: changeme
  ingress:
    enabled: true
    hosts:
      - jaeger.forex-platform.local
  query:
    options:
      query:
        base-path: /jaeger
  collector:
    options:
      collector:
        zipkin:
          host-port: :9411
  agent:
    strategy: DaemonSet
  ui:
    options:
      menu:
        - label: Grafana
          url: http://grafana:3000
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
