version: '3.8'

services:
  risk-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    environment:
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - HOST=0.0.0.0
      - PORT=8012
    volumes:
      - ./:/app
    networks:
      - forex-platform-network

networks:
  forex-platform-network:
    driver: bridge
