version: '3'

services:
  redis:
    image: redis:7-alpine
    container_name: forex_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --maxmemory 1gb --maxmemory-policy volatile-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
