apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-management-service
  name: portfolio-management-service
spec:
  ports:
  - name: http
    port: 8002
    targetPort: 8002
  selector:
    app: portfolio-management-service
