global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "/etc/prometheus/alerts/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Core Services
  - job_name: "analysis-engine-service"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["analysis-engine-service:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'analysis-engine-service'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'core'

  - job_name: "trading-gateway-service"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["trading-gateway-service:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'trading-gateway-service'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'core'

  - job_name: "feature-store-service"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["feature-store-service:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'feature-store-service'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'core'

  - job_name: "ml-integration-service"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["ml-integration-service:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'ml-integration-service'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'core'

  - job_name: "strategy-execution-engine"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["strategy-execution-engine:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'strategy-execution-engine'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'core'

  - job_name: "data-pipeline-service"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["data-pipeline-service:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'data-pipeline-service'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'core'

  # Support Services
  - job_name: "monitoring-alerting-service"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["monitoring-alerting-service:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'monitoring-alerting-service'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'support'

  # Infrastructure Monitoring
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'infrastructure'

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'infrastructure'

  # Database Monitoring
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'database'

  # Message Queue Monitoring
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'message-queue'

  # Redis Monitoring
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'cache'

  # Service Discovery for Dynamic Environments
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: replace
        target_label: service
      - source_labels: [__meta_kubernetes_pod_label_service_type]
        action: replace
        target_label: service_type