affinity: {}
autoscaling:
  enabled: true
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
config:
  database:
    host: postgres
    name: ui-service
    port: 5432
    user: postgres
  logging:
    format: json
    level: INFO
  metrics:
    enabled: true
    path: /metrics
  service:
    environment: production
    name: ui-service
    port: 8000
  tracing:
    enabled: true
    endpoint: jaeger-collector:4317
env:
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  SERVICE_NAME: ui-service
image:
  pullPolicy: IfNotPresent
  repository: forex-trading-platform/ui-service
  tag: latest
nodeSelector: {}
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
secrets:
  apiKey: secret-key
  dbPassword: password
service:
  port: 8000
  type: ClusterIP
tolerations: []
