global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: "market-data-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["market-data-service:8001"]

  - job_name: "analysis-engine-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["analysis-engine-service:8002"]

  - job_name: "trading-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["trading-service:8003"]

  - job_name: "feature-store-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["feature-store-service:8004"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]