apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading-gateway-service
  name: trading-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-gateway-service
  template:
    metadata:
      labels:
        app: trading-gateway-service
    spec:
      containers:
      - image: forex-trading-platform/trading-gateway-service:latest
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        name: trading-gateway-service
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
