apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading-gateway-service
  name: trading-gateway-service
spec:
  ports:
  - name: http
    port: 8001
    targetPort: 8001
  selector:
    app: trading-gateway-service
