# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis_engine_service/analysis_engine.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analysis_engine_service/analysis_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-analysis_engine_service/analysis_engine.proto\x12\x17\x61nalysis_engine_service\x1a\x0c\x63ommon.proto\"\xd9\x02\n\x0f\x41nalysisRequest\x12 \n\nrequest_id\x18\x01 \x01(\x0b\x32\x0c.common.UUID\x12\x19\n\x11instrument_symbol\x18\x02 \x01(\t\x12<\n\ranalysis_type\x18\x03 \x01(\x0e\x32%.analysis_engine_service.AnalysisType\x12%\n\nstart_time\x18\x04 \x01(\x0b\x32\x11.common.Timestamp\x12#\n\x08\x65nd_time\x18\x05 \x01(\x0b\x32\x11.common.Timestamp\x12L\n\nparameters\x18\x06 \x03(\x0b\x32\x38.analysis_engine_service.AnalysisRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9e\x02\n\x10\x41nalysisResponse\x12 \n\nrequest_id\x18\x01 \x01(\x0b\x32\x0c.common.UUID\x12!\n\x0b\x61nalysis_id\x18\x02 \x01(\x0b\x32\x0c.common.UUID\x12\x37\n\x06status\x18\x03 \x01(\x0e\x32\'.analysis_engine_service.AnalysisStatus\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x18\n\x10result_data_json\x18\x05 \x01(\t\x12$\n\ttimestamp\x18\x06 \x01(\x0b\x32\x11.common.Timestamp\x12\x31\n\x05\x65rror\x18\x07 \x01(\x0b\x32\x1d.common.StandardErrorResponseH\x00\x88\x01\x01\x42\x08\n\x06_error*r\n\x0c\x41nalysisType\x12\x1d\n\x19\x41NALYSIS_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eTREND_ANALYSIS\x10\x01\x12\x17\n\x13VOLATILITY_ANALYSIS\x10\x02\x12\x16\n\x12SENTIMENT_ANALYSIS\x10\x03*Y\n\x0e\x41nalysisStatus\x12\x1f\n\x1b\x41NALYSIS_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x32\x7f\n\x15\x41nalysisEngineService\x12\x66\n\x0fRequestAnalysis\x12(.analysis_engine_service.AnalysisRequest\x1a).analysis_engine_service.AnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_engine_service.analysis_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYSISREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_ANALYSISREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYSISTYPE']._serialized_start=725
  _globals['_ANALYSISTYPE']._serialized_end=839
  _globals['_ANALYSISSTATUS']._serialized_start=841
  _globals['_ANALYSISSTATUS']._serialized_end=930
  _globals['_ANALYSISREQUEST']._serialized_start=89
  _globals['_ANALYSISREQUEST']._serialized_end=434
  _globals['_ANALYSISREQUEST_PARAMETERSENTRY']._serialized_start=385
  _globals['_ANALYSISREQUEST_PARAMETERSENTRY']._serialized_end=434
  _globals['_ANALYSISRESPONSE']._serialized_start=437
  _globals['_ANALYSISRESPONSE']._serialized_end=723
  _globals['_ANALYSISENGINESERVICE']._serialized_start=932
  _globals['_ANALYSISENGINESERVICE']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
