
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.secrets.dbPassword | b64enc }}
  api-key: {{ .Values.secrets.apiKey | b64enc }}
