server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:55681
        grpc:
          endpoint: 0.0.0.0:4317

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: forex-trading-platform
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

overrides:
  sampling_rules:
    - service: trading-gateway-service
      name: order_execution
      type: ratio
      ratio: 1.0
    - service: data-pipeline-service
      name: market_data_processing
      type: ratio
      ratio: 0.1
    - service: "*"
      name: "*"
      type: ratio
      ratio: 0.01
