apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-integration-service
  name: ml-integration-service
spec:
  ports:
  - name: http
    port: 8006
    targetPort: 8006
  selector:
    app: ml-integration-service
