"""
GitHub Actions workflow for dependency analysis.
"""
name: Dependency Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze:
    name: Analyze Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydeps pylint networkx matplotlib

    - name: Analyze Python Dependencies
      id: python_deps
      run: |
        # Generate dependency graphs for each service
        for service in */; do
          if [ -f "$service/pyproject.toml" ] || [ -f "$service/setup.py" ]; then
            echo "Analyzing $service..."
            pydeps "$service" --only "$service" --show-cycles --max-bacon=2 \
              --cluster --output-format=svg --output="dependency-graphs/${service%/}.svg"
          fi
        done
        
        # Run custom dependency analyzer
        python tools/analyze_dependencies.py --report-file dependency-report.json

    - name: Check for Circular Dependencies
      run: |
        python tools/check_circular_deps.py --report-file dependency-report.json
        
    - name: Upload Dependency Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-analysis
        path: |
          dependency-graphs/
          dependency-report.json

    - name: Fail if New Cycles Detected
      if: steps.python_deps.outputs.new_cycles == 'true'
      run: |
        echo "New circular dependencies detected! Check the dependency report."
        exit 1
