name: Deploy Forex Trading Platform

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov
          
      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  build:
    name: Build Services
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Analysis Engine Service
        uses: docker/build-push-action@v4
        with:
          context: ./analysis-engine-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/forex-analysis-engine:latest
      
      - name: Build and push Feature Store Service
        uses: docker/build-push-action@v4
        with:
          context: ./feature-store-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/forex-feature-store:latest
      
      - name: Build and push Data Pipeline Service
        uses: docker/build-push-action@v4
        with:
          context: ./data-pipeline-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/forex-data-pipeline:latest
      
      - name: Build and push Trading Gateway Service
        uses: docker/build-push-action@v4
        with:
          context: ./trading-gateway-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/forex-trading-gateway:latest

  deploy:
    name: Deploy to Environment
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /path/to/deployment && docker-compose pull && docker-compose up -d"
      
      - name: Verify Deployment
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker ps | grep forex"
